### ISSUE TITLE
Issue: Roversa drive forward (number) does not appear to be changing the distance traveled

### ISSUE THREAD

**Issue by techkim** [eb8ga/pxt-roversa-2#2]
As I was testing a function lesson, I was updating the input into roversa.driveForwards() between 4 and 50 and there was no difference in the distance traveled.

Update: I tried adding calibrate drive amount to [on start] block and updated distance values from 50 to 200, but still no change.

Here's the MakeCode project where I first discovered the issue: https://makecode.microbit.org/S04772-14799-94026-93630

**Comment by eb8ga** [comment]
Had to add a separate function to ensure that the driveForward and driveBackward were not using the forward and backward functions since those were hardcoded distances.
